### ISSUE TITLE
#i with invalid path requires kernel restart to fix

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/interactive#1523] opened 2021-07-30 22:06 UTC
Executing this command when the directory doesn't exist breaks all subsequent #r nugets

````
#i "nuget:C:\Foo"
`````

![image](https://user-images.githubusercontent.com/5175830/127716063-1c82323f-b842-4379-933a-9fa4c8bab311.png)

Invalid executions should not break other cells.

**Comment by jonsequitur** [comment] 2021-08-01 15:18
This is a duplicate of #319.

**Closed** 2021-08-01 15:18 UTC
