### ISSUE TITLE
Documentation Missing: DisplayAs

### ISSUE THREAD

**Issue by mika76** [dotnet/interactive#2147] opened 2022-07-14 07:07 UTC
### Describe the bug
There is no real documentation on the `DisplayAs` functionality which was discussed at https://github.com/dotnet/interactive/issues/1983#issuecomment-1169491522 . It's really useful so I think it should at least be mentioned somewhere 😊

**Comment by jonsequitur** [comment] 2022-07-19 17:23
Closing as a duplicate of #2078.

**Closed by jonsequitur** 2022-07-19 17:23 UTC
Labels: Area-Documentation, duplicate
