### ISSUE TITLE
Command line invocation of dib files

### ISSUE THREAD

**Issue by onionhammer** [dotnet/interactive#892] opened 2020-11-18 18:30 UTC
Execute `dotnet interactive run file.dib -o report.md` to run the entire report and export as markdown or HTML. This would be great to be able to generate reports periodically that can be consumed by non-developers.

**Comment by jonsequitur** [comment] 2020-11-19 17:10
Thanks for the suggestion. This is something we're actively looking into. 

I'm going to close this as it's a duplicate of #483. Feel free to add suggestions there for how you'd like to see this work.

**Closed by jonsequitur** 2020-11-19 17:10 UTC
