### ISSUE TITLE
VS Notebook editor: unable to adjust zoom for code and markdown blocks

### ISSUE THREAD

**Issue by mrlucmorin** [dotnet/interactive#2159] opened 2022-07-20 01:04 UTC
### Describe the bug
Zoom level is only possible for output blocks. It should be available for all blocks.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

1.0.310301

- OS
    - [ ] Windows 11
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [X] Visual Studio
    - [ ] Other (please specify)

**Comment by zewditu** [comment] 2022-07-25 19:27
@jonsequitur , How do you reproduce this issue?

**Comment by mrlucmorin** [comment] 2022-07-27 22:29
1. Open a Notebook with the VS2022 Notebook editor 
2. Move your cursor over either a **Code** block, or a **Text** block
3. Try to use the mouse wheel (or keyboard shortcuts) to "zoom" the text size
4. Text size is not changed

Now, do the exact same thing with your mouse over an **Output** block, and watch as the text size shrinks/grows (as expected).

Let me know if you need more details.

**Comment by zewditu** [comment] 2022-08-10 21:46
As @luisquintanilla mentioned  in NET Interactive issues review chat this is inherited issue from the visual studio IDE. Visual studio has this know issue to zoom text.  The issue is not specific to Notebook rather inherited from VS.

**Comment by mrlucmorin** [comment] 2022-08-12 16:58
@zewditu ok, thanks for explaining. Would you happen to have a link to the issue on Visual Studio's tracker? I'd like to read the details. Cheers.

**Comment by claudiaregio** [comment] 2023-01-04 23:05
Closing as support for notebooks in VS has been discontinued

**Closed by claudiaregio** 2023-01-04 23:05 UTC
Labels: bug, External, Area-VisualStudio
