### ISSUE TITLE
Always copy FSharp.Core.xml on output

### ISSUE THREAD

**Issue by TIHan** [dotnet/interactive#871] opened 2020-11-10 18:55 UTC
We should be copying FSharp.Core.xml when we build so we get the appropriate documentation in interactive.
Related: https://github.com/dotnet/sdk/issues/9498

**Comment by dsyme** [comment] 2020-12-04 16:13
Duplicate of https://github.com/dotnet/interactive/issues/842?

**Comment by colombod** [comment] 2021-04-09 00:11
@KevinRansom, @brettfo  is this now fixed?

**Comment by KevinRansom** [comment] 2021-04-09 00:41
It's hard to say.

**Comment by KevinRansom** [comment] 2021-04-16 20:20
Always copying it, created an issue for F# developers.  So I made it an opt in switch, I will go through the notebook solution and make sure that we enable it when necessary/

**Comment by jonsequitur** [comment] 2021-04-16 22:26
Is the only way to solve the actual issue?

**Closed** 2023-01-31 18:27 UTC
Labels: bug, Area-F#, Area-Language Services
