### ISSUE TITLE
Very bad experience with default F# formatting in notebooks

### ISSUE THREAD

**Issue by gbaydin** [dotnet/interactive#1282] opened 2021-04-21 00:47 UTC
### Describe the bug
I'm opening this issue as a bug report as I'm quite confused about what was discussed and concluded in the previous related issue #642 and I haven't seen any changes in behavior in the latest dotnet interactive versions.

The problem is that the default formatter for F# values in notebooks does a really bad job, in turn making the user experience quite bad, and in my view unusable, by default. This is especially the case for a newcomer with lots of experience in Python and Juypter, trying out dotnet interactive.

We just need to have a simple plaintext printer by default, which mirrors the conventional Jupyter notebook experience with Python. This can be achieved by these two lines @dsyme kindly provided before:

```fsharp
Formatter.SetPreferredMimeTypeFor(typeof<obj>, "text/plain")
Formatter.Register(fun (x:obj) (writer: TextWriter) -> fprintfn writer "%120A" x )
```
Can you please make this the default in dotnet interactive for F#?

This is the single biggest problem with the user experience currently.

Screenshots of the default behavior and the updated behavior are attached below.

### Please complete the following:

**Which version of .NET Interactive are you using?**
1.0.211906+4b8eb267854eb055ef2f7b16561ebbcd6cc69b2e

- OS
    - [ ] Windows 10
    - [ ] macOS
    - [X] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [X] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots

Screenshot with bad user experience (the current default)
![image](https://user-images.githubusercontent.com/5365982/115479625-b7314c00-a240-11eb-9e13-240ad10af4dc.png)

Screenshot with acceptable user experience (after manually having to change the default F# formatter)
![image](https://user-images.githubusercontent.com/5365982/115479638-c1ebe100-a240-11eb-95b2-f760f42c1214.png)

**Comment by jonsequitur** [comment] 2021-04-21 01:16
I hear you. We are working on this one. 

The initial iteration on the formatters has global scope so that extensions that do more interesting HTML formatting (e.g. plots, help links for `System.Type`, actual images for graphic types) can apply across languages. And since C# has no equivalent to F#'s printers, we started with a common baseline. We're refining to allow each subkernel to have its own formatting at which point F# can default to FSI-style plain text output. But I suspect we can do even better. For example, #1233 can potentially be applied to other types (as discussed in #1257 and #1260).

I'm going to close this as a duplicate of #642 so as not to fork the conversation.

**Closed by jonsequitur** 2021-04-21 01:16 UTC

**Comment by gbaydin** [comment] 2021-04-21 02:00
@jonsequitur unfortunately my impression is that you don't hear me at all. 

The reason I opened this was to make the conversation very concrete and crystal clear: can we have the plaintext printer as the default for F# right now?

By closing this with pointers to #1233 #1257 #1260 etc, which seem to be about more html tables with even more bells and whistles, you haven't addressed the report and request I'm making here.

**Comment by colombod** [comment] 2021-04-21 13:56
> @jonsequitur unfortunately my impression is that you don't hear me at all.
> 
> The reason I opened this was to make the conversation very concrete and crystal clear: can we have the plaintext printer as the default for F# right now? Namely this thing which does the job of making dotnet interactive usable for me:
> 
> ```fsharp
> Formatter.SetPreferredMimeTypeFor(typeof<obj>, "text/plain")
> Formatter.Register(fun (x:obj) (writer: TextWriter) -> fprintfn writer "%120A" x )
> ```
> 
> By closing this with pointers to #1233 #1257 #1260 etc, which seem to be about more html tables with even more bells and whistles, you haven't addressed the report and request I'm making here.

Sorry but I don't understand. In his reply @jonsequitur says:
> We're refining to allow each subkernel to have its own formatting at which point F# can default to FSI-style plain text output. But I suspect we can do even better. For example, #1233 can potentially be applied to other types (as discussed in #1257 and #1260).

Formatter api will be improved so that each kernel can define more specific behavior. We hear you and other user feedback. Is a priority and we will get there.

**Comment by gbaydin** [comment] 2021-04-22 00:26
Note that my issue is specifically about default settings and a need to have plaintext as the default formatter.

The responses I have received were mostly about improving html tables and introducing even more complicated html tables that are the opposite of what I'm suggesting. This led to my comment of not being understood. 

But the conversation in #642 is now going a bit better and I'm cautiosly hopeful.

**Comment by jonsequitur** [comment] 2021-04-23 16:46
My intent was to say that we can change the F# defaults **_and also_** we would like input on the HTML formatters, which will be the default for C#, and will remain an option for F# users.

To make this clearer, I've opened a specific issue for changing the F# defaults: #1297.

**Comment by gbaydin** [comment] 2021-04-25 13:07
Thank you so much @jonsequitur for your response and patience. I've been really grumpy about this as it has affected my work for a long time and I believe it also affects the newcomer experience (primarily Python users trying F#/C#/dotnet in their browsers).
