### ISSUE TITLE
Adding extensions to the .NET kernel using nuget packages for F#

### ISSUE THREAD

**Issue by akshita31** [dotnet/interactive#84] opened 2019-08-22 20:09 UTC
**What is an extension ?**
An extension is anything that can be used to modify the behavior of the kernel without necessarily being checked into the kernel code. For example, if we would like the kernel to print "Hello World" after every successful code submission, it can be performed via adding an extension to the kernel.

**Possible applications of an extension**
1. Adding custom formatters for various types. For example, we can register a formatter for a dictionary which will display the keys and values in the dictionary in a table format with the keys in red color.
2. Support for various visualisation libraries. The Xplot Support that is present right now is done via the kernel extension. The kernel extension when loaded registers a formatter for the `XplotChart` type.
3. Support for magic commands like `%%javascript`. Such an extension would possible add a middleware that will read the code submitted and check if the magic command is present and do the evaluation accordingly.

**Existing implementation**
Right now an extension can be added to the kernel using the `#extend path_to_dll` directive. The problem with this approach is the acquisition story. Once extension author create extensions, how do they make their extension easily available to the notebook users.

**Proposed Implementation**
The extension can be a part of a nuget package. When a user does 
`#r "nuget:MyNugetPackage"` we look for a specific path inside the Nuget Package, say `/Extensions` and try to find all the implementations of `IKernelExtension` and load them into the kernel.

This approach can also be used to load scripts into the notebook context. Similar to the "Extensions", there can also be a `/Scripts` folder inside the nuget package containing the script files. We look for all those script files and pass `#load MyScript.csx` into the underlying script engine.

**Additional questions to be answered**
The .NET kernel has a `CompositeKernel` which has subkernels under it.
Let's take the case that the `CompositeKernel` has two subkernels - C# kernel and F# kernel. How does an extension specify if it is meant for C# kernel, F# kernel or if it is language agnostic and needs to be added to the composite kernel itself?

Also is there a way for the extension to get some piece of information from the kernel, like getting the compilation for the current cell and use that to emit a dll ?

**Comment by roberchi** [comment] 2020-03-23 17:11
Hi, one question on extension, how can install the kernel extensions? If I have a nuget or an assembly with the extension, is there any command to install it and used in a notebook without call #r nuget:xx .?

**Comment by jonsequitur** [comment] 2020-03-23 22:01
Currently, the way to install an extension is via `#r nuget`.

You can see the whole process, including source code, build, and installation, in this notebook: https://github.com/dotnet/interactive/blob/master/NotebookExamples/Extensions.ipynb

Is there an alternative approach that you would find useful?

**Comment by roberchi** [comment] 2020-03-23 23:45
> Currently, the way to install an extension is via `#r nuget`.
> 
> You can see the whole process, including source code, build, and installation, in this notebook: https://github.com/dotnet/interactive/blob/master/NotebookExamples/Extensions.ipynb
> 
> Is there an alternative approach that you would find useful?

It is useful but how I can load it like #!time directive that is loaded by the kernel at start time and not by #r directive?

**Comment by jonsequitur** [comment] 2020-03-24 17:51
`#r nuget` has functionality to scan the loaded package for extensions. If an extension dll is found in the correct location in the package, it's scanned for implementations of `IKernelExtension` and the handling `IKernel` is passed in. At that point, you can programmatically modify the kernel using the APIs in the `Microsoft.DotNet.Interactive` package.

You can see how those APIs work here:

![image](https://user-images.githubusercontent.com/547415/77459708-5fb27980-6dbd-11ea-9192-9bbf24a3d3a3.png)

**Comment by jonsequitur** [comment] 2020-09-23 20:47
Closing this as the current extension mechanism is simpler, by design. The kernel extension is not language or platform specific. The kernel can implement additional requirements via dependent packages if needed. We can revisit the issue as additional scenarios come up.

**Closed by jonsequitur** 2020-09-23 20:47 UTC
Labels: Area-Packages and Extensions, enhancement
