### ISSUE TITLE
can add js and html autocomplete feature 

### ISSUE THREAD

**Issue by wxyer** [dotnet/interactive#1566] opened 2021-08-28 03:28 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
no autocomplate make me hard too use,always type it error

**Describe alternatives you've considered**

**Comment by jonsequitur** [comment] 2023-08-08 15:53
I've opened a new issue and am closing this one as a duplicate of #3123.

**Closed by jonsequitur** 2023-08-08 15:53 UTC
Labels: duplicate, enhancement, Area-Language Services, Area-JavaScript HTML CSS
