### ISSUE TITLE
[VS Code] F# formatted print splits output into multiple lines

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/interactive#830] opened 2020-10-05 19:14 UTC
### Describe the bug

In the VS Code extension, printing formatted values splits the output into multiple lines.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

- .NET Interactive Version: 1.0.150105+6b0336d159c1643d967244f0047b44d42a0221b6
- .NET Interactive Notebooks extension: v1.0.150105
- VS Code Insiders Version: 1.50.0-insider

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/46974588/95121686-641cff00-071d-11eb-971d-74d72bf49b37.png)

**Comment by nodakai** [comment] 2021-07-28 17:53
Had the same problem with VSCode/Mac.

Use of string interpolation didn't help

`Console.Out.WriteLine` worked as expected (within .Net Interactive/F#)

**Comment by Ryan-Palmer-CIT** [comment] 2021-07-30 11:13
I just faced this too. Console.WriteLine is a workaround but it would be great if this got fixed so we can use printfn.

**Comment by jonsequitur** [comment] 2021-07-30 19:26
This should be fixed by #1514.

**Comment by jonsequitur** [comment] 2021-08-06 16:23
![image](https://user-images.githubusercontent.com/547415/128541675-7fe0bc8c-6a06-4cef-81a2-9dfb7a9d9f89.png)

**Closed** 2021-08-06 16:23 UTC
Labels: Area-VS Code Extension

**Comment by m4teiz** [comment] 2022-12-26 10:02
I still have this problem on VSCode/Mac after the update

**Comment by jonsequitur** [comment] 2022-12-27 20:14
@m4teiz, I'm not able to reproduce this. Can you show the output from running the `#!about` magic command?
