### ISSUE TITLE
Javascript code intellisense on VS Code

### ISSUE THREAD

**Issue by sanme98** [dotnet/interactive#2560] opened 2022-12-11 14:37 UTC
Polyglot notebooks don't have intellisense/autocomplete feature on VS Code. Is it possible to have this function? Thanks.

**Comment by jonsequitur** [comment] 2023-08-08 15:54
I've opened a new issue and am closing this one as a duplicate of #3123.

**Closed by jonsequitur** 2023-08-08 15:54 UTC
Labels: duplicate, enhancement, Area-Language Services, Area-JavaScript HTML CSS
