### ISSUE TITLE
Creating a new F# notebook switches initial cell to C# after saving

### ISSUE THREAD

**Issue by bmitc** [dotnet/interactive#2204] opened 2022-08-14 21:03 UTC
### Describe the bug

1. Open Visual Studio Code
2. Create a new blank notebook
3. Select "Create as '.dib'" (note: this bug doesn't happen if the `.ipynb` format is selected at this step)
4. Select "F#" as default language
5. Note that the initial cell is an F# cell
6. Save the notebook to disk
7. Note that the initial cell has now switched to a C# cell

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

```
Version: 1.0.340501+e6a4bd71118e0f7b202c761dd208cfa38bd5683b

Library version: 1.0.0-beta.22405.1+e6a4bd71118e0f7b202c761dd208cfa38bd5683b

Build date: 2022-08-12T03:08:59.0408371Z
```

- OS
    - [x] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

**Comment by AbhitejJohn** [comment] 2022-08-16 17:21
Gave this a quick shot today and this only repros if the first cell is empty. We also coalesce multiple empty cells and reset the language to C#. While the coalescing makes sense, we would want to review why we reset the language.

**Comment by bmitc** [comment] 2022-08-20 04:34
As a note, I have realized this only happens when creating `.dib` notebooks and not `.ipynb` notebooks.

**Comment by bmitc** [comment] 2022-08-26 05:04
This may be related to https://github.com/dotnet/interactive/issues/1324

**Comment by xperiandri** [comment] 2022-08-26 14:45
In Visual Studio it happens for `.ipynb` too
https://marketplace.visualstudio.com/items?itemName=MLNET.notebook

**Comment by xperiandri** [comment] 2022-08-26 14:46
Like I described in https://github.com/dotnet/interactive/issues/1827

**Comment by colombod** [comment] 2022-09-27 17:36
Closed as duplicate of #2289

**Closed** 2022-09-27 17:35 UTC
Labels: bug, Area-VS Code Extension, Impact-Low

**Comment by xperiandri** [comment] 2022-09-27 17:38
How are they connected?

**Comment by colombod** [comment] 2022-09-27 18:00
They relate to a bug in document metadata handling causing default languages to changedDr Diego Colombo PhDOn 27 Sep 2022, at 18:38, Andrii Chebukin ***@***.***> wrote:﻿
How are they connected?

**Comment by xperiandri** [comment] 2022-09-27 18:01
Ah, sorry. I was not attentive enough
