### ISSUE TITLE
Language detection disappears when this extension kernel is enabled

### ISSUE THREAD

**Issue by symisz** [dotnet/interactive#3119] opened 2023-08-04 09:17 UTC
creating a notebook file *.ipynb enables a language mode selection, this work when the extension is disabled.
once enabled, renders the selection to only two options which are "code" and markdown.

### environment & screenshots

.NET Interactive 7

- OS
    Windows 11
 - Frontend
    Visual Studio Code 

### Screenshots
Without kernel active:
![image](https://github.com/dotnet/interactive/assets/32195791/2ba8ed9f-6fab-4928-9948-cb3a2055b50a)

With kernel active:
![image](https://github.com/dotnet/interactive/assets/32195791/c12b1a00-9f3a-4d86-b406-e8120c12f1bc)

**Comment by jonsequitur** [comment] 2023-08-04 18:05
This is intentional, The language list in your first screenshot is the complete list of languages supported by VS Code, most of which don't work in notebooks. Polyglot Notebooks presents a list of languages that are actually supported when you click the cell kernel chooser in the lower-right corner of a cell:

<img width="639" alt="image" src="https://github.com/dotnet/interactive/assets/547415/97efc846-c1f7-4dee-899a-ae24ecaf316e">

**Comment by symisz** [comment] 2023-08-04 20:43
so is the lack of code completion or void of syntax highlight is suppose to be this way as well, this makes it less appealing to work with.

**Comment by symisz** [comment] 2023-08-07 10:52
I found the solution from another user @akselkvitberg 
Issue dating from December 2022 https://github.com/rose-pine/vscode/issues/76

you have to manual enable it in the settings,
code completion settings still not fully working.
feel free to share the settings to make code completion fully working in polyglot notebooks.

```json
    "editor.semanticHighlighting.enabled": true,
    "editor.suggestSelection": "first",
    "editor.suggest.snippetsPreventQuickSuggestions": true,
    "editor.acceptSuggestionOnEnter": "smart",
    "editor.quickSuggestions": {
        "comments": "on",
        "strings": "on",
        "other": "on"
    },
    "editor.suggestOnTriggerCharacters": true,
```

this issue also involves issue https://github.com/dotnet/interactive/issues/3113 @leet0rz

**Comment by leet0rz** [comment] 2023-08-07 12:04
@symisz Thank you, but how is there not a fix for this yet if the problem has been around since 2022. @jonsequitur - can something be done here?

**Comment by jonsequitur** [comment] 2023-08-07 22:41
If you're not seeing syntax highlighting and code completion, that is a bug and it's unrelated to the language chooser details above.

I'm unable to repro the lack of syntax highlighting described in  #3113. 

Completions work for most languages but not currently for JavaScript.

**Comment by leet0rz** [comment] 2023-08-08 05:59
> If you're not seeing syntax highlighting and code completion, that is a bug and it's unrelated to the language chooser details above.
> 
> I'm unable to repro the lack of syntax highlighting described in #3113.
> 
> Completions work for most languages but not currently for JavaScript.

Highlighting seems to work now for some reason, completion works for C# but not JavaScript. Do yo you plan on implementing it for JS at some point considering you are have it select-able in polyglot but it's not working as intended?

**Comment by jonsequitur** [comment] 2023-08-08 16:05
The main issue raised here is about the kernel chooser behavior which is intentionally different for Polyglot Notebooks than from other notebook extensions, so I'm closing this issue.

For JavaScript code completions, please refer to #3123.

**Closed by jonsequitur** 2023-08-08 16:05 UTC
