### ISSUE TITLE
Autocompletion not working for javascript in polyglot notebook.

### ISSUE THREAD

**Issue by leet0rz** [dotnet/interactive#3113] opened 2023-08-01 15:43 UTC
### Describe the bug
Just installed it and it did not work like in vscode otherwise.

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):
version: 7.0.306

- OS
    - [x] Windows 10
  
### Screenshots
An example, text not highlighted or anything so not working as otherwise in vscode:
https://i.imgur.com/iClp07k.png

**Comment by jonsequitur** [comment] 2023-08-01 19:00
This is a partial duplicate of #2560.

The missing code coloring is a different issue though. Where was the notebook running where you took the screenshot? I believe we've been seeing some code coloring issues in CodeSpaces but I can't reproduce this problem in VS Code.

<img width="384" alt="image" src="https://github.com/dotnet/interactive/assets/547415/2d735c34-e2cb-4c59-957b-9b664418599e">

**Comment by leet0rz** [comment] 2023-08-03 07:04
This was in vscode. Well, the syntax highlighting and code completion both are not working at all.

**Comment by jonsequitur** [comment] 2023-08-03 15:19
What version of VS Code are you using? 

Also, could you provide a screenshot of the output of the `#!about` magic command, including the lower right hand corner of the cell and the kernel chooser, like this: 

<img width="730" alt="image" src="https://github.com/dotnet/interactive/assets/547415/84a5e6ed-299b-410a-9e40-d406c5d6c311">

**Comment by leet0rz** [comment] 2023-08-03 18:44
vscode version:
https://i.imgur.com/6XSalfw.png

the about:
https://i.imgur.com/RgeAN9e.png

The scripts I put in there runs fine but the syntax highlighting and auto-completion is not there.

**Comment by jonsequitur** [comment] 2023-08-08 15:52
I've opened a new issue and am closing this one as a duplicate of #3123.

**Comment by jonsequitur** [comment] 2023-08-08 15:53
@leet0rz, if you see the syntax highlighting problem appear again, please open a new issue for it with as many details as you can provide.

**Closed by jonsequitur** 2023-08-08 15:53 UTC
Labels: duplicate, Area-Language Services, Area-JavaScript HTML CSS
