### ISSUE TITLE
Garbled Words (Simplified Chinese)

### ISSUE THREAD

**Issue by Orange23333** [dotnet/interactive#1061] opened 2021-02-12 17:00 UTC
### Describe the bug
C# Interactive display garbled code (currently simplified Chinese).

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
3.8.0-5.20604.10
(.NET SDK 5.0.103)

- OS
    - [x] Windows 10
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
 - Frontend
    - [x] Other : Visual Studio Community 2019 (16.8.5)

### Screenshots
![C#Interactive中文乱码](https://user-images.githubusercontent.com/18095289/107794390-598d0900-6d92-11eb-84e9-d77ec9546b87.PNG)

**Comment by jonsequitur** [comment] 2021-02-12 18:10
Thanks for reporting this.

This is a duplicate of https://github.com/dotnet/roslyn/issues/48874, which was fixed by https://github.com/dotnet/roslyn/pull/49721.

**Closed by jonsequitur** 2021-02-12 18:10 UTC
Labels: External
