### ISSUE TITLE
JavaScript variables are not being registered outside of cells

### ISSUE THREAD

**Issue by IntegerMan** [dotnet/interactive#2928] opened 2023-04-20 02:16 UTC
### Describe the bug
Apologies if this is a misunderstanding of kernel limitations.

I can import a C# variable into JavaScript without issues. However, if I declare a JS variable in a JS cell using either `let` or `const`, that variable does not seem to be registered in the variables section, is not available in the next cell (even if it's a JS cell), does not share correctly to C# or other kernels, and perhaps most interestingly, doesn't log out at the end of the same cell it was defined in if it was the closing value as in:

``` js
let jsVar = 42;
jsVar; // jsVar is not displayed after the cell
```

JavaScript otherwise appears to function just fine, but variable persistence and sharing just isn't working for me.

See https://github.com/IntegerMan/PolyglotNotebookTalk/blob/main/cs_js.dib for my sample notebook.

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

- OS
    - [x] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/5049957/233240199-2ab9b316-b1f5-45f2-86f3-c55e7c017d5f.png)

**Comment by jonsequitur** [comment] 2023-04-20 14:57
This is by design. The JavaScript kernel executes your code submission within a function, and so variables declared in that function aren't visible outside unless you use this syntax:

```javascript
x = 123;
```

By not using the `let`, `const`, or `var` keywords with your variable declaration, you're enabling JavaScript variable hoisting to make the variable visible to other cells (i.e. within other functions in the top-level scope).

As for return values from JavaScript cells, the trailing expression syntax isn't supported in JavaScript. So while in C# Script, this is equivalent to a `return` statement:

```csharp
123
```

in JavaScript you need to write this:

```javascript
return 123;
```

**Comment by IntegerMan** [comment] 2023-04-20 14:58
Thank you so much for the reply @jonsequitur. I'll play around with that tonight!

**Comment by jonsequitur** [comment] 2023-04-20 14:59
Looking forward to your thoughts. I'll update the docs with these details because it's unintuitive.

**Comment by jonsequitur** [comment] 2023-04-20 14:59
I'll keep the issue open for now and close it once the docs are updated.

**Comment by IntegerMan** [comment] 2023-04-22 19:32
So I've been playing with this and if I do:

```js
let jsVar = 42;
return jsVar;
```

I do see the value `42` after the cell, which is good, but no variable sharing occurs either. Is variable sharing just not possible between different JS cells in Polyglot?

**Comment by colombod** [comment] 2023-06-08 16:56
let / const  / var are scoped to the evaluation. to make them globally visible do
```js
jsVar = 42;
return jsVar;
```

**Closed** 2023-11-27 18:32 UTC
Labels: bug, Area-Documentation
