### ISSUE TITLE
No kernel found for SubmitCode - Microsoft.DotNet.Interactive

### ISSUE THREAD

**Issue by SQLvariant** [dotnet/interactive#440] opened 2020-05-18 21:29 UTC
### Describe the bug
I tried to run `$PSVersionTable` in Jupyter Notebook in Azure Data Studio using the .Net [interactive] PowerShell kernel, and then again using the Jupyter interface locally on my machine.  In both cases, I received the following error:
`Microsoft.DotNet.Interactive.NoSuitableKernelException: No kernel found for SubmitCode: $PSVersionTable
   at Microsoft.DotNet.Interactive.Commands.KernelCommandBase.InvokeAsync(KernelInvocationContext context) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\KernelCommandBase.cs:line 48
   at Microsoft.DotNet.Interactive.CompositeKernel.HandleAsync(IKernelCommand command, KernelInvocationContext context) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 182
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(IKernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 56
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 73
--- End of stack trace from previous location where exception was thrown ---`

**Which version of .NET Interactive are you using?** There are a few ways to find this out:
.NET Interactive
© 2020 Microsoft Corporation
Version: 1.0.126302+9e8f007038a86132f72a94889d805be2a14addf2
Build date: 2020-05-18T22:01:07.2566710Z

- OS
    - [x] Windows 10
 - Browser 
    - [x] Edge
 - Frontend
    - [x] Jupyter Notebook
    - [ ] Visual Studio Code
    - [x] Other - Azure Data Studio

### Screenshots
![image](https://user-images.githubusercontent.com/18595280/82261246-b1dec980-992c-11ea-8f15-663a47cea7fe.png)
![image](https://user-images.githubusercontent.com/18595280/82261296-c3c06c80-992c-11ea-908f-fc07ccc7e5cc.png)
![image](https://user-images.githubusercontent.com/18595280/82261349-d63aa600-992c-11ea-8b7f-54ce530a10dd.png)

**Comment by SQLvariant** [comment] 2020-05-18 21:39
To be clear, I followed the setup instructions on this page: https://github.com/dotnet/interactive/blob/master/docs/NotebooksLocalExperience.md

**Comment by jonsequitur** [comment] 2020-05-18 22:11
Which version of `dotnet-interactive` are you using?

**Comment by SQLvariant** [comment] 2020-05-18 22:23
I'm using the 3.1.2 .Net SDK (I originally put 3.1.4 in the description).  I just finished setting up everything today.

**Comment by jonsequitur** [comment] 2020-05-18 22:43
That's good. Thanks!

(The rest of the version string is the git commit hash.)

**Comment by jonsequitur** [comment] 2020-05-18 22:47
This could be a duplicate of #415. Can you try updating to a newer version of `dotnet-interactive`?

```console
> dotnet tool update -g Microsoft.dotnet-interactive --add-source "https://dotnet.myget.org/F/dotnet-try/api/v3/index.json"
```

**Comment by SQLvariant** [comment] 2020-05-18 22:56
Yes, running that command fixed it.

**Comment by jonsequitur** [comment] 2020-05-19 02:17
Thanks!

**Closed** 2020-05-19 02:17 UTC
Labels: waiting-on-feedback
