### ISSUE TITLE
Unable to copy text from step output

### ISSUE THREAD

**Issue by pakrym** [dotnet/interactive#668] opened 2020-07-27 16:27 UTC
### Describe the bug

Selecting text and pressing ctrl+c doesn't result in anything being copied from command output.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

![image](https://user-images.githubusercontent.com/1697911/88566647-2b5cfd00-cfeb-11ea-8ecd-3bb7677360ba.png)

```
Version: 1.48.0-insider (user setup)
Commit: 731f9c25632dbbf01ee3a7892ad9d2791fe0260c
Date: 2020-07-24T05:57:10.466Z (3 days ago)
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/1697911/88566770-55aeba80-cfeb-11ea-9670-318379132127.png)

**Comment by jonsequitur** [comment] 2020-07-27 17:03
This is a duplicate of #653.

**Closed** 2020-07-27 17:04 UTC
Labels: Area-VS Code Extension, bug, duplicate
