### ISSUE TITLE
[EXTERNAL] XPlot.Plotly overwites js render functions in markdown export

### ISSUE THREAD

**Issue by roy-t** [dotnet/interactive#696] opened 2020-08-09 13:20 UTC
# Describe the bug
If you have more than one plot, only the last plot will render in the exported markdown document. 

## Steps to reproduce:

1. Create a notebook with 2 plots
2. Export the notebook to Markdown using Juypter Lab's File -> Export NoteBook As menu.
3. Open the notebook in markdown viewer that allows exucuting javascript or convert the markdown file to HTML

## Cause:

Take a look at the script for displaying a graph (comments mine):
```
<script type="text/javascript">

var renderPlotly = function() {
    var xplotRequire = require.config({context:'xplot-3.0.1',paths:{plotly:'https://cdn.plot.ly/plotly-1.49.2.min'}}) || require;
    xplotRequire(['plotly'], function(Plotly) {
 // ...       
});
};
if ((typeof(require) !==  typeof(Function)) || (typeof(require.config) !== typeof(Function))) {
    // 1: Wait for script to download before rendering
    var script = document.createElement("script"); 
    script.setAttribute("src", "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js");
    script.onload = function(){
        renderPlotly();
    };
    document.getElementsByTagName("head")[0].appendChild(script); 
}
else {
    renderPlotly(); // 2: Render directly
}
</script>
```

As you see there are two moments when the plot can ben rendered
1. After `require.min.js` has been loaded
2. Directly, if the script is already present.

In an html export `require.min.js` is already loaded at the start of the document, so the script goes for option 2, which works correctly. In a markdown document the browser will start downloading and loading the `require.min.js` script only after it has encountered the first plot. 

This in itself is not a problem, however the `renderPlotly` function is overwritten by every plot. So once the browser has finished loading the script the `renderPlotly` function has been overwritten by the last plot and thus only the last plot will be rendered.

## Work around
There are two to work around this problem.
1. Include the following two lines at the start of your markdown file, this pre-loads the required scripts.
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
```
Or: 
2. Make sure that each plot has a uniquely named callback function for rendering. For example rename `renderPlotly` to `renderPlotly1` in the first div and `renderPlotly2` in the second div, etc...

# Please complete the following:
Running:
```
 .NET Interactive© 2020 Microsoft CorporationVersion: 1.0.140601+3c3cb20ba5952a6ac824e21b584218aae8df3fb6Build date: 2020-08-08T21:38:34.0881170Zhttps://github.com/dotnet/interactive
```
- OS
    - [X ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [X] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [X] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code
    - [ ] Other (please specify)

**Comment by jonsequitur** [comment] 2021-02-17 19:29
Marking this as external. 

Xplot integration is now supported via [Xplot.Plotly.Interactive](https://www.nuget.org/packages/XPlot.Plotly.Interactive/), which you can install in your notebook using the following:

```csharp
#r "nuget:xplot.plotly.interactive"
```

If the issue is still present, it should be addressed in the Xplot repo.

**Closed** 2021-02-17 19:29 UTC
Labels: Area-Visualization, External, bug
