### ISSUE TITLE
Can't share an array between F# and C# in a polyglot notebook

### ISSUE THREAD

**Issue by Bob-McCrory** [dotnet/interactive#1848] opened 2022-01-13 19:52 UTC
Tried creating a simple 2D array in C# and sharing it with F# for plotting. No luck. Only sees the first element in the array.

[PolyglotPlot00.zip](https://github.com/dotnet/interactive/files/7865562/PolyglotPlot00.zip)

Just let me know if you need anything else.

**Comment by PawelStadnicki** [comment] 2022-01-14 11:31
I don't know if this .NET interactive fault or C# -> F# intrisics
but notebooks, in general, should NOT be used the way you use them.

Between different language cells, you should pass simple objects.
In this case, you should pass to F# result of your computation, not "a tmp data holder" you probably  have (lala)

or just start all with F# , it will more readable.

You should use polyglot notebooks for actions that cannot be done in one language and another, not just mix languages for the sake of mixing languages

**Comment by jonsequitur** [comment] 2022-01-14 16:38
Mixing languages can be pretty interesting for learning, for comparing languages to one another, for copying from StackOverflow when you don't want to translate a sample, etc.

In any case, @Bob-McCrory, this does look like a bug. Just to compare like with like in terms of output, instead of using `printfn`, I did this, and it's surprising:

<img width="444" alt="image" src="https://user-images.githubusercontent.com/547415/149551467-5a480bf8-a8c5-4ecf-a6b8-bbe1d67091e6.png">

**Comment by Bob-McCrory** [comment] 2022-01-14 17:03
Pawel, thank you for your input.

My goal here was to convert an int array of cellular automata states computed in C# to an array in F# for plotting in Plotly.NET. I have found that the C# interface of Plotly.NET is very poorly documented, while I have successfully used it in F# in some of my other work. The example from the notebook was a toy example meant to see if this was possible; apparently, it isn't right now. My reasons for using both C# and F# are complicated and are not the issue right now.

I was mixing languages as a test. .NET Interactive failed. If polyglot notebooks are to be of any use at all, shouldn't a simple test like this be passed?


Bob

Robert T. McCrory, FSA
1532 East McGraw Street
Seattle, WA 98112-2134
206-323-7312
***@***.******@***.***>


________________________________

**Comment by Bob-McCrory** [comment] 2022-01-14 17:10
Thanks for looking into this, Jon. Your result is interesting, and it should be helpful to whoever is going to debug this.


Bob

Robert T. McCrory, FSA
1532 East McGraw Street
Seattle, WA 98112-2134
206-323-7312
***@***.******@***.***>


________________________________

**Comment by jonsequitur** [comment] 2022-01-14 17:17
This looks like it's specific to the F# compiler and multi-dimensional arrays. I haven't seen another bug like this one. Very interesting find!

**Comment by brettfo** [comment] 2022-01-14 21:44
Confirmed this is a bug in the F# repo.  I've filed issue dotnet/fsharp#12605 and am working on it now.

**Comment by brettfo** [comment] 2022-11-28 22:49
This has been fixed in #2018.

**Closed by brettfo** 2022-11-28 22:49 UTC
Labels: bug, Area-F#, Impact-Medium, External, Area-Variable sharing
