### ISSUE TITLE
Nuget Fails Trying To Access myget.org

### ISSUE THREAD

**Issue by andrewkittredge** [dotnet/interactive#1570] opened 2021-09-01 14:29 UTC
### Describe the bug
trying to install a nuget package from a notebook fails with an SSL error.

`#r "nuget:System.Text.Json"`
```
C:\Program Files\dotnet\sdk\5.0.300\NuGet.targets(131,5): error : Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json. [C:\Users\andre\AppData\Local\Temp\nuget\18104--6a40458f-6f49-4947-b211-13dd9000047e\Project.fsproj]
C:\Program Files\dotnet\sdk\5.0.300\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\Users\andre\AppData\Local\Temp\nuget\18104--6a40458f-6f49-4947-b211-13dd9000047e\Project.fsproj]
C:\Program Files\dotnet\sdk\5.0.300\NuGet.targets(131,5): error :   The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch [C:\Users\andre\AppData\Local\Temp\nuget\18104--6a40458f-6f49-4947-b211-13dd9000047e\Project.fsproj]
```
### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

Version: 1.0.243101+57612a802ef10cdbd305785db9aa9e60da8f8a56

- OS
    - [X ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [X ] Firefox
    - [ ] Safari
 - Frontend
    - [X ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/430274/131689110-a0df7072-92c8-4170-851f-4751fe2dbdf5.png)

**Comment by jonsequitur** [comment] 2021-09-01 16:38
This myget feed is no longer active.

**Comment by andrewkittredge** [comment] 2021-09-01 17:00
So why is nuget trying to access it?

**Comment by jonsequitur** [comment] 2021-09-01 17:06
You might have a reference to it in a nuget.config, such as your user-level nuget.config.

Run `dotnet nuget list source`  to check.

**Comment by andrewkittredge** [comment] 2021-09-01 17:16
When I run `dotnet nuget list source`

I get 

```
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  dotnet-core [Disabled]
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
  3.  Microsoft Visual Studio Offline Packages [Disabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

Is it possible that the nuget used by the #r cell-magic is not respecting the `[Disabled]` property?

**Comment by jonsequitur** [comment] 2021-09-01 18:15
Quite possibly, though if so it would be a NuGet bug. 

You can remove that entry from your nuget.config in any case, as that feed is no longer valid.

**Comment by KevinRansom** [comment] 2021-09-03 17:40
@andrew, it is possible, if so it's likely a dotnetsdk bug, I will take a look.

**Comment by james-murphy-maersk** [comment] 2021-09-07 09:16
@KevinRansom 

For what its worth I have similar issues - we have a validated feed for work and, well, it makes playing where I have no need for work packages harder than it could be. Feels like something in the "its not a bug its a feature" realm

**Comment by jonsequitur** [comment] 2021-11-09 00:13
@KevinRansom This looks external to .NET Interactive in any case. I'm going to close it. This should probably be taken up with the NuGet folks if we think it's a bug.

**Closed by jonsequitur** 2021-11-09 00:14 UTC
Labels: External

**Comment by sebastianbk** [comment] 2022-01-10 09:09
@andrewkittredge, did you find a solution to this issue?

**Comment by andrewkittredge** [comment] 2022-01-10 21:38
> @andrewkittredge, did you find a solution to this issue?

I think I removed myget from my nuget sources.

I gave up on dotnet/interactive.

**Comment by jonsequitur** [comment] 2022-01-10 23:09
If anyone is still experiencing this issue and doesn't have a myget link in one of their local nuget.config files, can you let us know which version you're using and some minimal repro steps, if different from the one stated at the top of the issue?
