### ISSUE TITLE
PowerShell Kernel - Focus of apps or prompts

### ISSUE THREAD

**Issue by wsmelton** [dotnet/interactive#174] opened 2020-02-17 04:55 UTC
#### Describe the bug
Creating a new notebook with the PowerShell kernel and finding that prompts or app windows are not coming into focus when being called from the notebook or from a PowerShell terminal (within JupyterLab).

#### Did this error occur while using `dotnet interactive`?
- [x] .NET Jupyter Notebook 

#### Screenshots
![image](https://user-images.githubusercontent.com/11204251/74624632-d0a3a900-510e-11ea-950e-2bc175102fe9.png)

An example use of calling this command from a Windows 10, with Hyper-V via a PowerShell notebook:

```
vmconnect $env:COMPUTERNAME $vmName
```

If you open a new terminal, selecting PowerShell and then just enter `Get-Credential` you will see this result:
![image](https://user-images.githubusercontent.com/11204251/74624739-43148900-510f-11ea-8729-68b11d6eb844.png)

(Windows Terminal in a PowerShell 7 session is how Jupyter Lab was started.)

Upon tapping on the Windows Terminal app I'm giving this view:

![image](https://user-images.githubusercontent.com/11204251/74624800-7eaf5300-510f-11ea-8fae-c90076500c4b.png)

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Safari
 - Frontend
    - [x] Jupyter notebook
    - [x] Jupyter lab
    - [ ] nteract

**Comment by SydneyhSmith** [comment] 2020-02-24 19:29
@wsmelton thanks for opening this issue, it appears that the issue you are hitting may be this: https://github.com/electron/electron/issues/11989 ...are you able to repro this in Windows Terminal?

**Comment by wsmelton** [comment] 2020-02-24 20:17
@SydneyhSmith no, the Windows Terminal changes focus on the `vmconnect` call as expected. Then with `Get-Credential` it does the terminal prompts (no form pop-up)...against as expected.

**Comment by daxian-dbw** [comment] 2020-02-26 18:20
This is by design. Please note that even though it looks like the Windows Terminal, but it's not actually running in Windows Terminal. It's likely just an xterm terminal in browser that is hooked up with powershell.exe running in 'jupyter-lab.exe'.

You can inspect the process tree by running the following code in the JupyterLab terminal:
```pwsh
$id = $PID
while ($true) {
    $p = Get-CimInstance -ClassName Win32_Process -Filter "ProcessId Like $id"
    if (!$p -or !$p.Name) { break }
    "{0}({1})" -f $p.ProcessName, $p.ProcessId
    $id = $p.ParentProcessId
}
```
This is what it will show you:

![image](https://user-images.githubusercontent.com/127450/75374365-066c2e80-5881-11ea-8268-b5dfc599e4aa.png)

As you will see, Windows Terminal is not in the process tree, and all processes are originated from the cmd.exe which is the `Anaconda Prompt`. That's why the focus is on that process.

**Comment by daxian-dbw** [comment] 2020-02-26 18:32
Some more investigation shows that the xterm terminal in browser is hooked up with pwoershell.exe through [winpty-agent.exe](https://github.com/rprichard/winpty), which acts like a bridge between the console API and terminal input/output escape codes.

**Comment by wsmelton** [comment] 2020-02-27 04:43
Maybe I'm mistaken but I haven't stated that is involved with Windows Terminal. I can get the same effect just starting the lab using cmd prompt or powershell.exe.

**Comment by daxian-dbw** [comment] 2020-02-27 23:49
I think this can be closed as "by design", @SydneyhSmith thoughts?

**Comment by SydneyhSmith** [comment] 2020-02-28 16:05
Thanks @daxian-dbw for the investigation, agreed that this is "by design"...if the user runs an interactive cmd like `Get-Credential` in a notebook cell it will prompt in the notebook as desired (with your latest changes), if it is run in the terminal the focus will shift to the host process

**Closed** 2020-02-28 18:25 UTC
Labels: PowerShell

**Comment by wsmelton** [comment] 2020-02-28 20:12
Just a note that using that command in a notebook does not work...

![image](https://user-images.githubusercontent.com/11204251/75583988-57705400-5a34-11ea-828c-14e9f2e8df46.png)

**Comment by SydneyhSmith** [comment] 2020-02-28 20:14
Thanks...potentially an early closure of this issue but this PR https://github.com/dotnet/interactive/pull/202 will allow for interactive prompting going forward
