### ISSUE TITLE
Intellisense performance degrades after using mssql kernel

### ISSUE THREAD

**Issue by colombod** [dotnet/interactive#1215] opened 2021-03-31 08:03 UTC
### Describe the bug
After creating a connection with `--create-dbcontext` option any intellisense function within c# cell is slow and and unresponsive

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code 
    - [X] Visual Studio Code Insiders
    - [ ] Other (please specify)

**Comment by colombod** [comment] 2021-04-12 14:03
First leg of work done with PRs #1232  and #1228

**Comment by jonsequitur** [comment] 2021-06-10 17:56
Close as duplicate of #1391. This issue is more general than just SQL.

**Closed by jonsequitur** 2021-06-10 17:56 UTC
Labels: Area-Language Services, Area-Performance, Impact-Medium, bug
