### ISSUE TITLE
Runaway energy usage by dotnet process after quitting VSCode

### ISSUE THREAD

**Issue by besttof** [dotnet/interactive#2527] opened 2022-11-29 20:03 UTC
### The bug

When I run some c# code in an interactive notebook in VS Code and then quit the application, within moments a new dotnet process is started. That dotnet process is instantly using 100% cpu and never seems to quit by itself. 

<img width="966" alt="image" src="https://user-images.githubusercontent.com/1409860/204634835-1c6c4ac8-9c08-43a8-854e-5b0e92251298.png">

Forgetting to force quit this process has now made it that VSCode is the number one power impact app on my laptop even when VS Code is not running:

<img width="963" alt="image" src="https://user-images.githubusercontent.com/1409860/204635381-bbd3459a-5c59-4af8-94d9-cab03f24e867.png">

### Info

Fontent: VS Code

>  Version: 1.0.355307+4cc71ae4e275fd80852b9c2faa317bc3a0033d2c
>  Library version: 1.0.0-beta.22553.7+4cc71ae4e275fd80852b9c2faa317bc3a0033d2c
>  Build date: 2022-11-04T02:20:42.0000000Z

OS: Ventura 13.0.1
MacBook Pro M1

**Comment by brettfo** [comment] 2022-12-02 16:43
We think this was addressed in #2466, but that fix is only in the version of the extension for VS Code - Insiders.  If you have that installed ([here](https://code.visualstudio.com/insiders/)) could you try it there?

**Comment by BryanWilhite** [comment] 2023-01-07 23:05
I have the same issue on Linux:

Does this issue occur when all extensions are disabled?: No
This issue is caused by the [Polyglot Notebooks extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode) (currently in Preview)

VS Code Version: 
```console
code --version
1.74.2
e8a3071ea4344d9d48ef8a4df2c097372b0c5161
x64
```
 
OS Version: 

```console
OS: Ubuntu 22.04.1 LTS x86_64 
Host: MINIPC PB50 0602 
Kernel: 5.15.0-57-generic 
Uptime: 3 hours, 36 mins 
Packages: 2641 (dpkg), 52 (snap) 
Shell: bash 5.1.16 
Resolution: 2560x1440 
DE: GNOME 
WM: Mutter 
WM Theme: Yaru-dark 
Theme: Yaru-olive-dark [GTK2/3] 
Icons: Yaru-olive [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8) @ 2.300GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
Memory: 6787MiB / 30020MiB 
```


Steps to Reproduce:

1.  Open a folder containing `*.ipynb` files in VSCode
2. Open an  `*.ipynb` file by double-clicking on it
3. Verify that a the notebook kernel is loaded and the expected content is visible
4. Close the `*.ipynb` file in VSCode
5. Close VSCode

You should see one or more orphaned/runaway processes like this (in **System Monitor**):

![image](https://user-images.githubusercontent.com/5226627/211173206-a4cf15a0-41ea-43d4-8f09-77d0f63724d5.png)

**Comment by mjbvz** [comment] 2023-01-11 02:37
Also saw this recently on MacOS after returning to my computer after being away from a few hours

![Screenshot 2023-01-10 at 6 30 51 PM](https://user-images.githubusercontent.com/12821956/211704804-5a390508-b9f1-4481-9aae-31de7044bcc6.png)

Polyglot notebooks `v1.0.4059041`
VS Code : 1.75.0-insider (Universal) Commit: e7b5449579249db344d473370d56a5df9446c826

Quitting VS Code insiders didn't stop the dotnet processes, I had to manually kill them

**Closed** 2023-01-24 12:25 UTC
Labels: bug, Area-VS Code Extension, waiting-on-feedback, Impact-High
