### ISSUE TITLE
Image in !#about is broken 

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/interactive#442] opened 2020-05-19 01:36 UTC
.NET Logo image link in the !#about broken 
![image](https://user-images.githubusercontent.com/2546640/82274894-5d991100-994f-11ea-87ce-1113aa5fb99c.png)
![image](https://user-images.githubusercontent.com/2546640/82274910-6ee21d80-994f-11ea-9a3e-c393c3acec4c.png)

**Comment by jonsequitur** [comment] 2020-05-19 01:39
This is a duplicate of #432.

**Closed** 2020-05-19 02:29 UTC
Labels: bug, duplicate
