### ISSUE TITLE
Documentation Missing: Entity Framework

### ISSUE THREAD

**Issue by mika76** [dotnet/interactive#2146] opened 2022-07-14 07:03 UTC
### Describe the bug
There seems to be no information documenting the Entity Framework connectivity - which was shown at https://devblogs.microsoft.com/dotnet/net-interactive-with-sql-net-notebooks-in-visual-studio-code/ but seems to be out of date

**Comment by jonsequitur** [comment] 2022-07-19 17:25
Closing as a duplicate of #2078.

**Closed by jonsequitur** 2022-07-19 17:25 UTC
Labels: Area-Documentation, Area-SQL / data querying
