### ISSUE TITLE
Microsoft.DotNet.Interactive.NoSuitableKernelException: No kernel found for SubmitCode:

### ISSUE THREAD

**Issue by oitptobbe** [dotnet/interactive#415] opened 2020-05-15 08:56 UTC
#### Describe the bug
When creating a powershell notebook I get the following error on any code run through the notebook
Microsoft.DotNet.Interactive.NoSuitableKernelException: No kernel found for SubmitCode: for($x=0;$x -lt 100; $x++) {
  write-progress -i ...
   at Microsoft.DotNet.Interactive.Commands.KernelCommandBase.InvokeAsync(KernelInvocationContext context) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\KernelCommandBase.cs:line 48

Same thing when running a console with powershell as the kernel.
write-host "Hello"
Microsoft.DotNet.Interactive.NoSuitableKernelException: No kernel found for SubmitCode: write-host "Hello"
   at Microsoft.DotNet.Interactive.Commands.KernelCommandBase.InvokeAsync(KernelInvocationContext context) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\KernelCommandBase.cs:line 48
   at Microsoft.DotNet.Interactive.CompositeKernel.HandleAsync(IKernelCommand command, KernelInvocationContext context) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 182
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(IKernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 56
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.Interactive.KernelBase.HandleDirectivesAndSubmitCode(SubmitCode submitCode, KernelInvocationContext context, KernelPipelineContinuation continueOnCurrentPipeline) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelBase.cs:line 149
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.Interactive.KernelBase.SetKernel(IKernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelBase.cs:line 124
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.Interactive.KernelBase.<>c.<<AddCaptureConsoleMiddleware>b__18_0>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelBase.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in F:\workspace\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 69

MBP:~ user$ jupyter kernelspec list
Available kernels:
  .net-csharp        /Users/tobias/Library/Jupyter/kernels/.net-csharp
  .net-fsharp        /Users/tobias/Library/Jupyter/kernels/.net-fsharp
  .net-powershell    /Users/tobias/Library/Jupyter/kernels/.net-powershell
  python2            /usr/local/share/jupyter/kernels/python2

MBP:~ user$ jupyter lab
Content root path: /Users/user/.dotnet/tools/.store/microsoft.dotnet-interactive/1.0.126302/microsoft.dotnet-interactive/1.0.126302/tools/netcoreapp3.1/any/

Works fine with .net c# and .net f#.

MBP:~ user$ pwsh -v
PowerShell 7.0.0

I've also tested dotnet tool install powershell (and also with -g but no change).

#### Did this error occur while using `dotnet interactive`?
- [x] .NET Jupyter Notebook 

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [x] Edge
    - [x] Safari
 - Frontend
    - [x] Jupyter notebook
    - [x] Jupyter lab
    - [ ] nteract

**Comment by jonsequitur** [comment] 2020-05-15 15:16
Thanks. We're working on a fix for this. 

You can work around it by adding the `#!pwsh` magic command before each cell in a C# or F# notebook, or by manually editing your PowerShell `kernel.json` (which you can find by running `jupyter kernelspec list` in a Jupyter-aware prompt) to change the default kernel name from "powershell" to "pwsh".

**Closed** 2020-05-15 20:07 UTC
Labels: bug

**Comment by eosfor** [comment] 2023-10-11 19:49
@jonsequitur, it feels like when i start a cell, im my case in powershell and hover a mouse cursor over any text in that cell i get this

```
Error: Microsoft.DotNet.Interactive.NoSuitableKernelException: No kernel found for Microsoft.DotNet.Interactive.Commands.RequestHoverText with target kernel 'pwsh'.
at Microsoft.DotNet.Interactive.Commands.KernelCommand.InvokeAsync(KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\KernelCommand.cs:line 183
at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 324
at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 60
at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 51
```

**Comment by jonsequitur** [comment] 2023-10-11 21:02
Could you provide a screen shot?

**Comment by eosfor** [comment] 2023-10-11 21:15
![image](https://github.com/dotnet/interactive/assets/9363027/aaa6800a-ac8b-4b39-a037-083b929ccb16)

@jonsequitur , this is a different issue though, looks like the correct place  is https://github.com/dotnet/interactive/issues/3244. Sorry for the confusion

**Comment by olebhartvigsen** [comment] 2023-10-12 11:26
I can confirm, same error here.
