### ISSUE TITLE
Hang upon execute cell while waiting for input

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/interactive#2240] opened 2022-08-30 22:23 UTC
Repro steps are intermittent or might just be a first launch after VSCode or extension installation.

The general repro steps are:
1. Open the folder for interactive in VSCode
2. Open the NotebookTestScript.dib
3. Scroll down to the “vscode kernel and user input prompts” section.
4. Press the execute cell button for the first interactive cell in that section.
Expected: A prompt opens at the top of the screen asking for input.
Actual: The prompt never opened and VSCode became unresponsive. The timer kept counting up but wasn’t stoppable.

Dmp file at: *externaldrive*\public\v-masche\dumps\interactiveInput.dmp

**Comment by jonsequitur** [comment] 2022-09-08 18:49
This is a duplicate of #2081.

**Closed by jonsequitur** 2022-09-08 18:49 UTC
Labels: bug, duplicate, Urgency-High
