### ISSUE TITLE
FSharp printfn goes on multiple line for every variable within the string

### ISSUE THREAD

**Issue by Nordes** [dotnet/interactive#1008] opened 2021-01-25 14:39 UTC
### Describe the bug
When I use `print` or `printfn` in FSharp, it prints every variable on a new line instead of being embedded in the text. I would expect the same as a `console.writeline` from C# + interpolated strings. (see screenshot below)

Maybe I miss a configuration somewhere or it's a bug ;). That being said, in the FSharpi (interactive) it works properly when in console.

### Please complete the following:

* In a notebook, run the `#!about` magic command. 
.NET Interactive© 2020 Microsoft CorporationVersion: 1.0.207203+f90ff415badc98a82c7db599658df94ad527328aBuild date: 2021-01-25T13:35:10.8046283Zhttps://github.com/dotnet/interactive

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots

Visual studio Notebook + Fsharp
![image](https://user-images.githubusercontent.com/446572/105719963-de51d900-5ef0-11eb-81f3-9bbbd904e96b.png)

Fsharp interactive (console)
![image](https://user-images.githubusercontent.com/446572/105720263-3b4d8f00-5ef1-11eb-9dc2-fa3ac9658c8d.png)

**Comment by jonsequitur** [comment] 2021-01-25 18:32
Thanks!

This is a duplicate of #799, so I'm going to close this one.

**Closed by jonsequitur** 2021-01-25 18:32 UTC
Labels: duplicate
