### ISSUE TITLE
Mixing C# and and F# reverts back to C#

### ISSUE THREAD

**Issue by Curtis-64** [dotnet/interactive#1196] opened 2021-03-29 03:07 UTC
### Describe the bug
Please provide as much information as you can.

In the lower right cell corner, the selection to change between C#/F# does not seem to stay after execution of cell. Going back to cell reverts back to C#.  I can force it with the magic command. But it still shows as C# in the lower right.

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
1.0.217604

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [X ] Visual Studio Code Insiders
    - [ ] Other (please specify)

**Comment by WalternativE** [comment] 2021-03-29 18:46
I can preproduce this too.

- .NET Interactive: 1.0.217604+a3dea7ced5d5f206116fcaec5d3f2ff5c2542e77
-  VSCode Insider: 1.55.0-insider (Commit 26a60d)
-  Jupyter Extension: v2021.5.697286501

**Comment by jonsequitur** [comment] 2021-03-29 20:29
I'm closing this as a duplicate of #1175.

**Closed by jonsequitur** 2021-03-29 20:29 UTC
Labels: duplicate
